version: '3.8'

services:
  # Ollama service for AI model
  ollama:
    image: ollama/ollama:latest
    container_name: hinglish-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama/models
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    # GPU support (uncomment if you have NVIDIA GPU)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Hinglish audio processing service
  hinglish-service:
    build: 
      context: ./hinglish-service
      dockerfile: Dockerfile
    container_name: hinglish-processor
    ports:
      - "8000:8000"
    volumes:
      - ./audio_temp:/app/temp
      - ./tts_models:/app/models
    environment:
      - OLLAMA_URL=http://ollama:11434
      - COQUI_MODEL_PATH=/app/models
      - DEFAULT_HINDI_VOICE=hi_male_glow
      - TEMP_DIR=/app/temp
      - LOG_LEVEL=INFO
    depends_on:
      - ollama
    restart: unless-stopped
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Next.js frontend application
  nextjs-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hinglish-nextjs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws
      - NEXT_PUBLIC_SUPPORT_HINDI=true
      - NEXT_PUBLIC_DEFAULT_LANG=hinglish
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - hinglish-service
    restart: unless-stopped

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: hinglish-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - nextjs-app
      - hinglish-service
    restart: unless-stopped
    profiles:
      - production

volumes:
  ollama_data:
    driver: local
  tts_models:
    driver: local

networks:
  default:
    name: hinglish-network 